name: campus_connect
description: A university lost and found + student union platform.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # âš™ï¸ State Management
  provider: ^6.1.2

  # ðŸ’¬ UI & Animation
  flutter_svg: ^2.0.7
  lottie: ^2.7.0
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.2.1
  iconsax: ^0.0.8

  # ðŸ“¸ Image Picker (for lost items)
  image_picker: ^1.1.1

  # ðŸŒ Others
  intl: ^0.19.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.3.0
  url_launcher: ^6.3.0
  http: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: PirataOne
      fonts:
        - asset: assets/fonts/PirataOne-Regular.ttf
